name: GimSwap

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create diff
        run: |
          mkdir -p diff
          git remote add target https://github.com/GimSwap/gimswap-frontend.git
          git fetch target dev
          git diff FETCH_HEAD > $GITHUB_WORKSPACE/diff/changes.diff

      - name: Backup diff
        run: cp $GITHUB_WORKSPACE/diff/changes.diff $HOME/changes.diff

      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: GimSwap/gimswap-frontend
          token: ${{ secrets.GIMSWAP_GITHUB_TOKEN }}
          ref: dev
          fetch-depth: 0

      - name: Restore diff
        run: |
          mkdir -p diff
          mv $HOME/changes.diff $GITHUB_WORKSPACE/diff/changes.diff

      - name: Convert line endings
        run: |
          sed -i 's/\r$//' $GITHUB_WORKSPACE/diff/changes.diff

      - name: Apply diff
        run: |
          git apply --check $GITHUB_WORKSPACE/diff/changes.diff || echo "적용할 변경 사항이 없습니다."
          git apply $GITHUB_WORKSPACE/diff/changes.diff || echo "적용할 변경 사항이 없습니다."

      - name: Commit changes
        run: |
          git config --global user.email "admin@gimswap.com"
          git config --global user.name "GimSwap"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Apply changes from main repo"
          else
            echo "No changes to commit"
          fi

      - name: Push changes
        run: git push origin dev
        env:
          GITHUB_TOKEN: ${{ secrets.GIMSWAP_GITHUB_TOKEN }}
